### PR TITLE
Fix: add width to images within placeholders

### PR DESCRIPTION
**Pull request by i-like-robots**
https://jira.ft.com/browse/NFT-541

For reference: The implementation of placeholders in cards differs slightly from that in articles as the article content transform will define the true image width (if smaller than a defined max width), [see here](https://github.com/Financial-Times/n-content-transform/blob/master/server/figure-variant.js).

### CODE REVIEW

**Comment by bjfletcher** [comment]
unless you hear from @ironsidevsquincy about this, I'd do some testing.

`npm link` this, and then `bower link n-card` and `npm link @financial-times/n-card` in homepage, stream and myFT apps.

Don't forget to update the ES6 modules list to include `n-card`, to fix a `bower link` oddity.

Then check all's looking ok on: homepage, myFT page, News Feed, Search (with a search keyword), World, and BP (company) pages.

I'm sorry if all this is a pain, but `n-card` is quite core and takes up much of next.ft.com.

**Comment by i-like-robots** [comment]
Fortunately testing this change was easy - I monkey patched it in while browsing the site.

The change should only affect lazy-loaded images that are smaller than the generated placeholder which occur rarely (card images already define a `max-width` rule and `max-height` on streams).

**Comment by bjfletcher** [comment]
How did you monkey patch it in? Charles?

**Comment by i-like-robots** [comment]
Much more simple - a [CSS injection plugin](https://chrome.google.com/webstore/detail/styler/bogdgcfoocbajfkjjolkmcdcnnellpkb?hl=en) =]

**Pull request merged**
