### PR TITLE
Premium label styling

### PR DESCRIPTION
**Pull request by leggsimon**
@i-like-robots @andygout 

From:
screenshot 2016-10-27 17 31 30

To:
screenshot 2016-10-27 17 30 58

### CODE REVIEW

**Comment by i-like-robots** [comment]
like a glove

**Comment by leggsimon** [comment]
Will release tomorrow

**Comment by andygout** [comment]
Worth checking how this affects different sizes of Premium labels elsewhere (hard-coding Premium value to true so all places labels can potentially be displayed present themselves):

#### Before
before

#### After
after

**Comment by leggsimon** [comment]
@andygout Yeah just did that and looks ok on all cards

**Pull request merged**
