### PR TITLE
Fix: IE image w/content overlay background gradient

### PR DESCRIPTION
**Pull request by andygout**
@ironsidevsquincy

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Does it need to be a gradient at all? Those MS filter things have pretty horrendous performance.

**Comment by andygout** [comment]
Potentially not. Will speak to designer (we are getting a new one this week) and see what an acceptable fallback would be.

Would it be okay to add now so we have it working on IE9 in the meantime?

**Comment by ironsidevsquincy** [comment]
I would say we should be pragmatic about it and use our own judgement - if we know trying to achieve this will have a detrimental performance cost, and it's only for a dwindling browser, we should just do what we think's best. 
Once something is out there, it's harder to revert it
(that's my personal opinion anyway)

**Comment by ironsidevsquincy** [comment]
👍

**Pull request merged**
